import argparse
import hashlib
import json
import math
import os
import tempfile
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any

from advice_journal import load_entries, resolve_journal_path


OUTCOME_EVIDENCE_VERSION = "1.0"


def _resolved_path(path: str | Path) -> Path:
    return Path(path).expanduser().resolve(strict=False)


def _same_file(left: Path, right: Path) -> bool:
    if left == right:
        return True
    try:
        return left.exists() and right.exists() and left.samefile(right)
    except OSError:
        return False


def _atomic_write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=str(path.parent), text=True
    )
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_path, path)
    except Exception:
        try:
            temporary_path.unlink(missing_ok=True)
        except OSError:
            pass
        raise


def _mean(values: list[float]) -> float | None:
    return round(sum(values) / len(values), 2) if values else None


def _format_pct(value: float | None, signed: bool = True) -> str:
    if value is None:
        return "N/A"
    return f"{value:+.2f}%" if signed else f"{value:.2f}%"


def _sample_type(entry: dict[str, Any]) -> str:
    explicit = entry.get("calibration_sample_type")
    if explicit in {"research", "execution"}:
        return str(explicit)
    return "legacy_mixed"


def _finite_number(value: Any) -> float | None:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return None
    parsed = float(value)
    return parsed if math.isfinite(parsed) else None


def _canonical_digest(value: Any) -> str:
    encoded = json.dumps(
        value, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def _is_sha256(value: Any) -> bool:
    if not isinstance(value, str) or len(value) != 64:
        return False
    try:
        int(value, 16)
    except ValueError:
        return False
    return True


def _iso_datetime(value: Any) -> datetime | None:
    if not isinstance(value, str) or not value:
        return None
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None


def _evidence_error(entry: dict[str, Any]) -> str | None:
    if entry.get("calibration_sample_type") not in {"research", "execution"}:
        return "legacy or untyped entries are archive-only"
    if not isinstance(entry.get("dual_trigger_detected"), bool):
        return "dual_trigger_detected must be an explicit boolean generated by sync_outcomes"
    evidence = entry.get("outcome_evidence")
    if not isinstance(evidence, dict):
        return "verified sync_outcomes evidence contract is missing"
    supplied_digest = evidence.get("evidence_sha256")
    digest_input = {key: value for key, value in evidence.items() if key != "evidence_sha256"}
    if (
        evidence.get("contract_version") != OUTCOME_EVIDENCE_VERSION
        or evidence.get("generator") != "sync_outcomes.py"
        or not isinstance(supplied_digest, str)
        or supplied_digest != _canonical_digest(digest_input)
    ):
        return "sync_outcomes evidence contract or digest is invalid"

    source = evidence.get("source")
    if (
        not isinstance(source, dict)
        or not isinstance(source.get("provider"), str)
        or not source["provider"].strip()
        or not isinstance(source.get("locator"), str)
        or not source["locator"].strip()
        or source.get("daily_interval") != "1d"
    ):
        return "daily source provider, locator, and interval are required"

    coverage = evidence.get("daily_coverage")
    start_time = _iso_datetime(entry.get("calibration_start_date"))
    outcome_time = _iso_datetime(entry.get("outcome_date"))
    if start_time is None or outcome_time is None:
        return "calibration start and outcome dates are required"
    for side in ("asset", "benchmark"):
        item = coverage.get(side) if isinstance(coverage, dict) else None
        first_time = _iso_datetime(item.get("first_timestamp")) if isinstance(item, dict) else None
        last_time = _iso_datetime(item.get("last_timestamp")) if isinstance(item, dict) else None
        if (
            not isinstance(item, dict)
            or not isinstance(item.get("row_count"), int)
            or item["row_count"] <= 0
            or first_time is None
            or last_time is None
            or first_time.date() > start_time.date()
            or last_time.date() < outcome_time.date()
            or not _is_sha256(item.get("content_sha256"))
        ):
            return "asset and benchmark daily coverage summaries are required"

    summary = evidence.get("result_summary")
    if not isinstance(summary, dict):
        return "outcome result summary is required"
    exact_fields = (
        "calibration_start_date",
        "outcome_date",
        "outcome_resolution_method",
        "dual_trigger_detected",
    )
    if any(summary.get(field) != entry.get(field) for field in exact_fields):
        return "outcome result summary does not match the journal entry"
    numeric_fields = (
        "calibration_start_price",
        "outcome_price",
        "outcome_return_pct",
        "benchmark_return_pct",
        "net_excess_return_pct",
    )
    for field in numeric_fields:
        left = _finite_number(summary.get(field))
        right = _finite_number(entry.get(field))
        if left is None or right is None or left != right:
            return "outcome result summary numeric fields do not match the journal entry"

    if entry["dual_trigger_detected"] is False:
        if evidence.get("intraday_sequence") is not None:
            return "non-dual-trigger evidence must not contain an intraday sequence"
        return None

    if (
        entry.get("dual_trigger_policy") != "exclude"
        or entry.get("calibration_quality") != "observed_intraday"
        or entry.get("outcome_resolution_method") != "intraday_first_trigger"
    ):
        return "dual-trigger formal calibration requires exclude policy and observed intraday resolution"
    sequence = evidence.get("intraday_sequence")
    summary_sequence = sequence.get("sequence_summary") if isinstance(sequence, dict) else None
    trigger_time = _iso_datetime(sequence.get("trigger_timestamp")) if isinstance(sequence, dict) else None
    benchmark_time = _iso_datetime(sequence.get("benchmark_timestamp")) if isinstance(sequence, dict) else None
    sequence_first = (
        _iso_datetime(summary_sequence.get("first_timestamp"))
        if isinstance(summary_sequence, dict)
        else None
    )
    sequence_last = (
        _iso_datetime(summary_sequence.get("last_timestamp"))
        if isinstance(summary_sequence, dict)
        else None
    )
    if (
        not isinstance(sequence, dict)
        or sequence.get("provider") != source["provider"]
        or sequence.get("locator") != source["locator"]
        or sequence.get("interval") in (None, "", "1d")
        or sequence.get("first_trigger") not in {"downside_boundary", "upside_boundary"}
        or trigger_time is None
        or trigger_time.tzinfo is None
        or benchmark_time is None
        or benchmark_time.tzinfo is None
        or sequence.get("trigger_timestamp") != entry.get("outcome_resolution_timestamp")
        or not isinstance(summary_sequence, dict)
        or summary_sequence.get("interval") != sequence.get("interval")
        or not isinstance(summary_sequence.get("rows_on_trigger_date"), int)
        or summary_sequence["rows_on_trigger_date"] <= 0
        or not isinstance(summary_sequence.get("rows_reviewed_through_trigger"), int)
        or summary_sequence["rows_reviewed_through_trigger"] <= 0
        or summary_sequence["rows_reviewed_through_trigger"]
        > summary_sequence["rows_on_trigger_date"]
        or sequence_first is None
        or sequence_first.tzinfo is None
        or sequence_last is None
        or sequence_last.tzinfo is None
        or not (sequence_first <= trigger_time <= sequence_last)
        or not _is_sha256(summary_sequence.get("content_sha256"))
    ):
        return "dual-trigger intraday sequence metadata is incomplete or inconsistent"
    return None


def _formally_eligible(entry: dict[str, Any]) -> bool:
    if entry.get("calibration_eligible") is not True:
        return False
    if _finite_number(entry.get("net_excess_return_pct")) is None:
        return False
    horizon = _finite_number(entry.get("investment_horizon_days"))
    if horizon is None or horizon <= 0:
        return False
    if entry.get("calibration_quality") == "assumption_based_conservative":
        return False
    return _evidence_error(entry) is None


def _formal_exclusion_reason(entry: dict[str, Any]) -> str:
    if entry.get("calibration_quality") == "assumption_based_conservative":
        return "conservative dual-trigger result is sensitivity only"
    if _finite_number(entry.get("net_excess_return_pct")) is None:
        return "net excess return must be a finite JSON number"
    horizon = _finite_number(entry.get("investment_horizon_days"))
    if horizon is None or horizon <= 0:
        return "investment horizon must be positive and finite"
    evidence_error = _evidence_error(entry)
    if evidence_error:
        return evidence_error
    return str(entry.get("calibration_exclusion_reason") or "not eligible")


def calculate_calibration(entries: list[dict[str, Any]]) -> dict[str, Any]:
    eligible = [
        entry
        for entry in entries
        if _formally_eligible(entry)
    ]
    observed = list(eligible)
    research_samples = [entry for entry in eligible if _sample_type(entry) == "research"]
    execution_samples = [entry for entry in eligible if _sample_type(entry) == "execution"]
    legacy_mixed_samples = [entry for entry in entries if _sample_type(entry) == "legacy_mixed"]
    executed_research = [entry for entry in research_samples if entry.get("executed") is True]
    not_executed_research = [entry for entry in research_samples if entry.get("executed") is not True]

    sensitivity_values = []
    for entry in entries:
        sensitivity = entry.get("sensitivity_analysis")
        sensitivity_value = (
            _finite_number(sensitivity.get("net_excess_return_pct"))
            if isinstance(sensitivity, dict)
            else None
        )
        if sensitivity_value is not None:
            sensitivity_values.append(sensitivity_value)
        elif (
            entry.get("calibration_quality") == "assumption_based_conservative"
            and _finite_number(entry.get("net_excess_return_pct")) is not None
        ):
            sensitivity_values.append(float(entry["net_excess_return_pct"]))

    net_returns = [float(entry["net_excess_return_pct"]) for entry in observed]
    research_returns = [float(entry["net_excess_return_pct"]) for entry in research_samples]
    executed_research_returns = [
        float(entry["net_excess_return_pct"]) for entry in executed_research
    ]
    not_executed_research_returns = [
        float(entry["net_excess_return_pct"]) for entry in not_executed_research
    ]
    by_horizon: dict[int, list[float]] = defaultdict(list)
    by_confidence: dict[str, list[float]] = defaultdict(list)
    for entry in observed:
        horizon = int(entry["investment_horizon_days"])
        by_horizon[horizon].append(float(entry["net_excess_return_pct"]))
        by_confidence[str(entry.get("confidence_level") or "unknown")].append(
            float(entry["net_excess_return_pct"])
        )
    exclusion_reasons = Counter(
        _formal_exclusion_reason(entry)
        for entry in entries
        if entry not in eligible
    )
    return {
        "eligible": eligible,
        "eligible_count": len(eligible),
        "observed_count": len(observed),
        "research_sample_count": len(research_samples),
        "execution_sample_count": len(execution_samples),
        "legacy_mixed_sample_count": len(legacy_mixed_samples),
        "executed_research_subset_count": len(executed_research),
        "not_executed_research_subset_count": len(not_executed_research),
        "assumption_based_count": len(sensitivity_values),
        "sensitivity_count": len(sensitivity_values),
        "excluded_count": len(entries) - len(eligible),
        "average_net_excess_return_pct": _mean(net_returns),
        "research_average_net_excess_return_pct": _mean(research_returns),
        "assumption_based_average_net_excess_return_pct": _mean(sensitivity_values),
        "sensitivity_average_net_excess_return_pct": _mean(sensitivity_values),
        "executed_research_subset_average_pct": _mean(executed_research_returns),
        "not_executed_research_subset_average_pct": _mean(not_executed_research_returns),
        "positive_excess_hit_rate_pct": (
            round(sum(value > 0 for value in net_returns) / len(net_returns) * 100, 2)
            if net_returns
            else None
        ),
        "research_positive_excess_rate_pct": (
            round(
                sum(value > 0 for value in research_returns)
                / len(research_returns)
                * 100,
                2,
            )
            if research_returns
            else None
        ),
        "by_horizon": {
            horizon: {"count": len(values), "average_net_excess_return_pct": _mean(values)}
            for horizon, values in sorted(by_horizon.items())
        },
        "by_confidence": {
            confidence: {"count": len(values), "average_net_excess_return_pct": _mean(values)}
            for confidence, values in sorted(by_confidence.items())
        },
        "exclusion_reasons": dict(exclusion_reasons),
    }


def build_report(journal_path: str | None = None) -> str:
    entries = load_entries(journal_path)
    calibration = calculate_calibration(entries)
    average = calibration["research_average_net_excess_return_pct"]
    hit_rate = calibration["research_positive_excess_rate_pct"]
    lines = [
        "# Research Outcome Calibration Report",
        "",
        f"- 生成时间: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"- 日志文件: {resolve_journal_path(journal_path)}",
        "- 决策范围: research_only",
        f"- 总样本数: {len(entries)}",
        f"- 所有正式合格样本数: {calibration['eligible_count']}",
        f"- 正式研究样本数: {calibration['research_sample_count']}",
        f"- 执行结果样本数: {calibration['execution_sample_count']}",
        f"- 历史混合口径样本数: {calibration['legacy_mixed_sample_count']}",
        f"- conservative 敏感性样本数: {calibration['sensitivity_count']}",
        f"- 排除样本数: {calibration['excluded_count']}",
        f"- 正式研究样本平均相对收益率: {_format_pct(average)}",
        f"- 正相对收益研究样本占比: {_format_pct(hit_rate, signed=False)}",
        f"- conservative 敏感性平均相对收益率: {_format_pct(calibration['sensitivity_average_net_excess_return_pct'])}",
        "",
        "> 正式研究指标只统计明确标记为 research 的样本，不以 executed=True 作为入样条件。历史混合口径与执行结果单列；日线同时触及观察下界和上界且盘中顺序不可核验时，正式校准一律排除，conservative 结果仅列入敏感性。",
        "",
        "## 执行选择分层",
        "",
        f"- 研究样本中的已执行子集: {calibration['executed_research_subset_count']}，平均相对收益率 {_format_pct(calibration['executed_research_subset_average_pct'])}",
        f"- 研究样本中的未执行或未披露子集: {calibration['not_executed_research_subset_count']}，平均相对收益率 {_format_pct(calibration['not_executed_research_subset_average_pct'])}",
        "",
        "> 该分层用于暴露执行选择偏差，不代表真实交易绩效，也不生成任何交易指令。",
        "",
        "## 分期限校准",
        "",
        "| 期限（天） | 样本数 | 平均净超额收益率 |",
        "|---:|---:|---:|",
    ]
    if calibration["by_horizon"]:
        for horizon, item in calibration["by_horizon"].items():
            lines.append(
                f"| {horizon} | {item['count']} | {item['average_net_excess_return_pct']:+.2f}% |"
            )
    else:
        lines.append("| - | 0 | N/A |")

    lines.extend(["", "## 置信度校准", "", "| 置信度 | 样本数 | 平均净超额收益率 |", "|:---|---:|---:|"])
    if calibration["by_confidence"]:
        for confidence, item in calibration["by_confidence"].items():
            lines.append(
                f"| {confidence} | {item['count']} | {item['average_net_excess_return_pct']:+.2f}% |"
            )
    else:
        lines.append("| - | 0 | N/A |")

    lines.extend(["", "## 样本排除原因", ""])
    if calibration["exclusion_reasons"]:
        for reason, count in sorted(calibration["exclusion_reasons"].items()):
            lines.append(f"- {reason}: {count}")
    else:
        lines.append("- 无")

    lines.extend(
        [
            "",
            "## 正式可校准样本",
            "",
            "| 日期 | 标的 | 样本层 | 已执行 | 期限 | 质量 | 解析方法 | 标的收益 | 基准收益 | 相对收益 |",
            "|:---|:---|:---:|:---:|---:|:---|:---|---:|---:|---:|",
        ]
    )
    for entry in sorted(calibration["eligible"], key=lambda item: item.get("created_at", ""), reverse=True):
        lines.append(
            "| {date} | {symbol} | {sample_type} | {executed} | {horizon} | {quality} | {method} | {asset:+.2f}% | {benchmark:+.2f}% | {excess:+.2f}% |".format(
                date=str(entry.get("created_at", ""))[:10],
                symbol=entry.get("stock_name") or entry.get("stock_code"),
                sample_type=_sample_type(entry),
                executed="是" if entry.get("executed") is True else "否/未披露",
                horizon=entry.get("investment_horizon_days"),
                quality=entry.get("calibration_quality") or "observed",
                method=entry.get("outcome_resolution_method") or "legacy",
                asset=float(entry.get("outcome_return_pct", 0)),
                benchmark=float(entry.get("benchmark_return_pct", 0)),
                excess=float(entry.get("net_excess_return_pct", 0)),
            )
        )
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate benchmark-aware calibration from an advice journal.")
    parser.add_argument("--journal-path")
    parser.add_argument(
        "--output-path",
        default=os.environ.get("PIA_CALIBRATION_REPORT"),
        help="Required output path; alternatively set PIA_CALIBRATION_REPORT.",
    )
    args = parser.parse_args()
    if not args.output_path:
        parser.error("output path is required; pass --output-path or set PIA_CALIBRATION_REPORT")
    journal_path = _resolved_path(resolve_journal_path(args.journal_path))
    output_path = _resolved_path(args.output_path)
    if _same_file(output_path, journal_path):
        parser.error("output path must not resolve to the advice journal input")
    report = build_report(str(journal_path))
    _atomic_write_text(output_path, report)
    print(f"report written: {output_path}")
