"""
<!-- Input: Project Path, Output Filename -->
<!-- Output: Merged Report Path, Density Audit Report -->
<!-- Pos: scripts/assembler.py. The "Blacksmith" that forges the final report. -->

!!! Maintenance Protocol: This script MUST verify character counts before and after merge.
!!! ANY loss of data > 0 bytes results in a failure code.
"""

import argparse
import os
import glob
import sys

def assemble_report(project_path, output_filename="final_report.md"):
    # 1. Locate Chapters
    # Matches chapter_01.md, chapter_1.md, chapter_v1.md
    search_pattern = os.path.join(project_path, "chapter*.md")
    files = glob.glob(search_pattern)
    
    # Sort carefully (1, 2, 10 instead of 1, 10, 2)
    # Heuristic: extract first number found in filename
    try:
        files.sort(key=lambda x: int(''.join(filter(str.isdigit, os.path.basename(x))) or 999))
    except:
        files.sort() # Fallback

    if not files:
        return {"status": "error", "message": "No chapter files found."}

    # 2. Audit Source Density
    total_source_bytes = sum(os.path.getsize(f) for f in files)
    
    # 3. Physical Concatenation
    merged_content = []
    merged_content.append(f"""# Strategic Deep Dive Report
> Generated by Research Analyst V6.0

""")
    
    for f_path in files:
        with open(f_path, 'r', encoding='utf-8') as f:
            merged_content.append(f.read())
            merged_content.append("""

---

""") # Separation
    
    final_text = "".join(merged_content)
    
    # 4. Save
    output_path = os.path.join(project_path, output_filename)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(final_text)
    
    # 5. Density Guard Check
    final_bytes = os.path.getsize(output_path)
    # Allow small overhead for headers/newlines
    loss_ratio = 1 - (final_bytes / (total_source_bytes + 1)) 
    
    status = "success"
    if loss_ratio > 0.05: # >5% loss is suspicious
        status = "warning_density_loss"
    
    return {
        "status": status,
        "path": output_path,
        "chapters_merged": len(files),
        "source_bytes": total_source_bytes,
        "final_bytes": final_bytes
    }

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--path", required=True)
    parser.add_argument("--output", default="final_report.md")
    args = parser.parse_args()
    
    result = assemble_report(args.path, args.output)
    print(result)

if __name__ == "__main__":
    main()
