"""
<!-- Standard Header -->
@Input: Adversarial Fragments (00_*.md, 01_*.md, ...)
@Output: Final Audit Report (Vulnerability Vault)
@Pos: Phase 4 (Archival)
@Maintenance Protocol: Prefix logic (00-99) must be preserved for sorting.
"""
import os
import sys
import glob

def merge_adversarial_fragments(workspace_path, output_file_path):
    """
    Consolidates round-by-round adversarial fragments into a single report.
    Adds section headers and formatting for a professional audit experience.
    """
    if not os.path.isdir(workspace_path):
        print(f"Error: Adversary workspace {workspace_path} not found.")
        sys.exit(1)

    pattern = os.path.join(workspace_path, "*.md")
    fragments = sorted(glob.glob(pattern))

    if not fragments:
        print(f"Error: No .md audit fragments found in {workspace_path}.")
        sys.exit(1)

    print(f"Merging {len(fragments)} fragments for final audit: {workspace_path}")
    
    try:
        with open(output_file_path, 'w', encoding='utf-8') as outfile:
            outfile.write("# FINAL LOGIC AUDIT REPORT (Vulnerability Vault)\n\n")
            outfile.write("> Generated by Logic Adversary V6.0 (Mentat-led Audit)\n\n---\n\n")
            
            for fragment_path in fragments:
                fname = os.path.basename(fragment_path)
                print(f" - Integrating Audit Node: {fname}")
                
                with open(fragment_path, 'r', encoding='utf-8') as infile:
                    content = infile.read()
                    outfile.write(content)
                    if fragment_path != fragments[-1]:
                        outfile.write("\n\n---\n\n")
        
        print(f"Final Audit Vault created at: {output_file_path}")
    except Exception as e:
        print(f"Audit merge failed: {e}")
        sys.exit(1)

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python session_merger.py <workspace_path> <output_file_path>")
        sys.exit(1)
    
    workspace = sys.argv[1]
    output = sys.argv[2]
    merge_adversarial_fragments(workspace, output)
